# Generated by Django 6.0.6 on 2026-07-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Central', 'Central'), ('Gujarat', 'Gujarat')], default='Central', max_length=20)),
                ('description', models.TextField(default='')),
                ('benefits', models.TextField(default='')),
                ('eligibility', models.TextField(default='')),
                ('official_link', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='app1.state')),
            ],
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdistrict_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talukas', to='app1.district')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('soil_type', models.CharField(choices=[('Black', 'Black'), ('Red', 'Red'), ('Alluvial', 'Alluvial'), ('Clay', 'Clay'), ('Sandy', 'Sandy'), ('Loamy', 'Loamy')], max_length=30)),
                ('language', models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi')], default='English', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.state')),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.taluka')),
            ],
        ),
    ]
