# Generated by Django 6.0.6 on 2026-09-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_farmer_user_alter_farmer_password_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandiPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('market', models.CharField(db_index=True, max_length=150)),
                ('commodity', models.CharField(db_index=True, max_length=150)),
                ('variety', models.CharField(blank=True, default='Other', max_length=100)),
                ('grade', models.CharField(blank=True, default='FAQ', max_length=50)),
                ('arrival_date', models.DateField(db_index=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(default='₹/Quintal', max_length=50)),
                ('source', models.CharField(default='data.gov.in / Agmarknet', max_length=150)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-arrival_date', 'market', 'commodity'],
                'indexes': [models.Index(fields=['state', 'district'], name='app1_mandip_state_cf0384_idx'), models.Index(fields=['commodity', 'modal_price'], name='app1_mandip_commodi_8e17be_idx'), models.Index(fields=['arrival_date', 'market'], name='app1_mandip_arrival_8bddb3_idx')],
                'unique_together': {('state', 'district', 'market', 'commodity', 'variety', 'arrival_date')},
            },
        ),
    ]
