# Generated by Django 6.0.6 on 2026-10-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_mandiprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('sowing', 'Crop Sowing'), ('irrigation', 'Irrigation Reminder'), ('fertilizer', 'Fertilizer Application'), ('crop_care', 'General Crop Care'), ('harvesting', 'Harvesting Reminder'), ('weather_alert', 'Weather Alert'), ('government_scheme', 'Government Scheme'), ('market_price', 'Market Price'), ('crop_advisory', 'Crop Advisory'), ('system', 'System')], default='crop_care', max_length=30),
        ),
    ]
